### ISSUE TITLE
当请求内容为一个json数组时，提示的却是“不是json格式”

### ISSUE THREAD

**Issue by xiancloud** [xiancloud/xian#31]
错误日志如下：
```
info.xiancloud.gateway.scheduler.body_not_required.ReqBodyParseFailure:
http请求内容不符合规范，不是json格式
```

应当提示为"json array is not allowed, please use json instead."

**Comment by happyyangyuan** [comment]
fixed, tip is changed to 'http request body is not a standard json object string, please check'
